version: '3.8'
services:
  db:
    image: postgres:15 # Use the same major version as Supabase was using
    restart: always
    environment:
      POSTGRES_DB: cursorforwriting_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local 